### PR TITLE
jsclock

### PR DESCRIPTION
**Pull request by Midhuna-sudo**
Build a JavaScript clock

### CODE REVIEW

**Comment by Tejas1510** [comment]
Good work @Midhuna-sudo 
Just add your file in a folder and then raise a pr having the folder

**Comment by Midhuna-sudo** [comment]
Sir could you please tell how to add it in a file

**Comment by Tejas1510** [comment]
Just create a folder name jsclock and add your javascript file inside the folder and while creating a PR add the complete folder instead of the single file

**Comment by Midhuna-sudo** [comment]
I'm unable to do it

**Comment by Tejas1510** [comment]
@Midhuna-sudo see it is very easy 
Just create a folder name jsclock and add your javascript file inside the folder
Then fork my repo then add your folder by simply drag and drop method and create a PR

**Comment by Midhuna-sudo** [comment]
Sir with patience could you explain in each step please I'm a beginner

**Comment by Tejas1510** [comment]
@Midhuna-sudo 
As I said the process is very simple
1. create a folder name clock and add your javascript file inside the folder
2. Fork My repository
3. Now in the forked repository there will be an option to add files their select upload file
4. Now just drag your complete folder and drop in the upload section.
5. Commit all the file using the button present at the bottom
6.Now Raise a PR
7 You are Done with the request

**Pull request closed without merging**
