### PR TITLE
Added Enrollment Project

### PR DESCRIPTION
**Pull request by prikshitsetia**
Enrollment Project in Flask
To run 
1. Create a virtual environment with venv
2. run the venv with venv\Scripts\activate
3. install all the dependencies
4. run the command flask run

### CODE REVIEW

**Comment by Tejas1510** [comment]
Great work @prikshitsetia

**Comment by prikshitsetia** [comment]
Thank You😀

**Comment by Tejas1510** [comment]
Try adding a readme to your project so others using it may find easy to run
your code

**Comment by prikshitsetia** [comment]
Sure, will do that

**Pull request merged**
